#!/usr/bin/env node
/* Writes rules-data.js: the rulebook's text (rules.js, with the engine's numbers already in it) and the facts the cover states, as window.RULES,
   so manual.html can be opened from disk and the engine can embed it. A different engine setting changes the words here, never in the layout. */
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const SOURCE = path.join(__dirname, '..'), CFG = JSON.parse(fs.readFileSync(path.join(SOURCE, 'game.json'), 'utf8'));
const S = require(path.join(SOURCE, CFG.sim)), RULES = require(path.join(SOURCE, 'rules.js'));
const R = { sourceHash: crypto.createHash('sha256').update(fs.readFileSync(path.join(SOURCE, CFG.sim))).digest('hex'), title: CFG.name, tagline: CFG.tagline, players: CFG.players, minutes: CFG.minutes, defaults: S.RULES, lid: RULES.lid, pages: RULES.pages };
fs.writeFileSync(path.join(__dirname, 'rules-data.js'), '/* Generated by sync-rules.js from rules.js and the engine; edit those, not this. */\nwindow.RULES = ' + JSON.stringify(R, null, 1) + ';\n');
console.log('Synced the rulebook text from rules.js.');
