/* ORCHARD's words: what is engraved inside the lid (the rules at a glance) and what the rulebook says, page by page. One place for every sentence
   a player reads, so the lid, the aid and the book never disagree. Plain sentences in everyday words. Numbers come from the engine's RULES.
   UMD: node (module.exports) or the page's worker (root.GameRules). */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require('./orchard-sim.js'));
  else root.GameRules = factory(root.OrchardSim);
})(typeof globalThis !== 'undefined' ? globalThis : this, function (S) {
  'use strict';
  const R = S.RULES;
  const lid = {
    title: 'ORCHARD · how to play',
    intro: `Pick fruit, deliver orders, fly the crow at your rivals. The first farmer to deliver ${R.ordersToEnd} orders ends the game; the round is finished so everyone has had the same turns. Most points wins.`,
    columns: [
      { heading: 'Walk and pick', text: `On your turn, walk your farmer up to ${R.moves} trees in a straight or bent line, never through or onto another farmer. Then pick one fruit from the tree you stand at, into your basket. Your basket holds ${R.basket} fruit. A tree with the crow on it gives nothing.` },
      { heading: 'Deliver, then the crow', text: `If your basket holds every fruit an order needs, deliver it: pay the fruit back to the supply and keep the card. Deliver one of your ${R.handSize} secret orders or one of the ${R.market} at the market; a market order is replaced from the deck. Then fly the crow 1 to ${R.crowMoves} trees on along its path. A farmer on the tree it lands on loses one fruit, and the crow brings it to you.` },
    ],
    footer: `The game ends when someone has delivered ${R.ordersToEnd} orders or a fruit runs out, at the end of that round. Points on your delivered cards, less the points of any secret order still in your hand; a fuller basket breaks a tie.`,
  };
  /** the rulebook's pages: [kicker, title, html body]. The manual's build lays them out; figures name assets the manual captures from the cut files */
  const pages = [
    ['Welcome', 'A season in the orchard', `<p>Four farmers share one orchard of sixteen trees. Every tree grows one fruit: apples, pears, plums or cherries. Orders come in from the village, each wanting a few fruit, and the farmer who fills the most valuable ones wins the season.</p><p>A crow lives in the orchard too. After every turn the farmer who just played flies it a little way along the rows, and a farmer standing where it lands loses a fruit to it.</p><figure><img class="part" src="assets/tile-apple.svg" style="height:34mm" alt="an apple tree tile"><img class="part" src="assets/farmer-red.svg" style="height:34mm" alt="a farmer"><img class="part" src="assets/crow.svg" style="height:24mm" alt="the crow"><figcaption><b>Fig. 1.</b> A tree, a farmer and the crow, as they are cut.</figcaption></figure>`],
    ['Components', 'What is in the box', `<ul><li>16 tree tiles, four of each fruit</li><li>1 barn tile with the scarecrow standing in it</li><li>4 farmers on their bases, one per colour, and 4 basket trays</li><li>1 crow on its base</li><li>${R.tokensPerKind * S.FRUITS.length} fruit tokens, ${R.tokensPerKind} of each fruit</li><li>${S.ORDERS.length} order cards</li></ul><figure><img class="part" src="assets/token-apple.svg" style="height:14mm" alt="an apple token"><img class="part" src="assets/token-pear.svg" style="height:14mm" alt="a pear token"><img class="part" src="assets/token-plum.svg" style="height:14mm" alt="a plum token"><img class="part" src="assets/token-cherry.svg" style="height:14mm" alt="a cherry token"><figcaption><b>Fig. 2.</b> The four fruit.</figcaption></figure>`],
    ['Setup', 'Planting the orchard', `<p>Shuffle the sixteen tree tiles face down and lay them out in a square of four by four, then turn them over. Put the barn beside the orchard.</p><p>Each farmer takes the farmer and basket board of one colour and stands the farmer on the numbered corner tree shown inside the box: seat 1 on corner 1, and so on round the table. The crow starts on the tree marked inside the box.</p><p>Put the fruit tokens in the lid, sorted by fruit. Shuffle the order cards. Deal ${R.handSize} to each farmer, kept secret, and turn ${R.market} face up beside the barn as the market. The rest are the deck.</p><figure><img class="part" src="assets/floor-base.svg" style="height:60mm" alt="the setup map inside the box"><figcaption><b>Fig. 3.</b> The setup map is engraved inside the base of the box.</figcaption></figure>`],
    ['Your turn', 'Walk, pick, deliver, and the crow', `<p>On your turn, do these in order.</p><ol><li><b>Walk.</b> Move your farmer up to ${R.moves} trees, each step to a tree beside the one you are on (not diagonal). You may not pass through or stop on a tree where another farmer stands. You may stay where you are.</li><li><b>Pick.</b> Take one fruit token of the tree's kind from the lid into your basket. Your basket holds ${R.basket} fruit at most. If the crow is on your tree, you pick nothing.</li><li><b>Deliver.</b> If your basket holds every fruit an order card needs, you may deliver it: put those fruit back in the lid and keep the card face down in front of you. You may deliver one of your secret orders or one from the market. Refill the market from the deck.</li><li><b>The crow.</b> Fly the crow 1, 2 or ${R.crowMoves} trees on along its path, the snake shown inside the box. If a farmer stands on the tree it lands on, that farmer gives up one fruit of their choice: it goes into your basket if there is room, else back into the lid.</li></ol>`],
    ['Your turn', 'A full basket', `<p>If your basket is full and you cannot deliver anything, you may put one fruit back in the lid before you pick.</p><figure><img class="part" src="assets/basket-red-frame.svg" style="height:26mm" alt="a basket tray's pocket layer"><figcaption><b>Fig. 4.</b> A basket tray holds four fruit in its pockets.</figcaption></figure><p>Fruit tokens are limited: ${R.tokensPerKind} of each. When a kind runs out, nobody can pick it until an order returns some.</p>`],
    ['Orders', 'The cards', `<p>Each order card names the fruit it needs and the points it is worth. Two-fruit orders are worth ${S.ORDERS[0].pts}, three-fruit orders ${S.ORDERS[4].pts}, and the Harvest festival, one of each, ${S.ORDERS[10].pts}: the big orders pay for the turns they take.</p><figure><img class="part" src="assets/order-4.svg" style="height:50mm" alt="the Fruit salad order"><img class="part" src="assets/order-10.svg" style="height:50mm" alt="the Harvest festival order"><figcaption><b>Fig. 5.</b> Two orders.</figcaption></figure><p>Nobody else can take your secret orders, but they are promises: a secret order still in your hand when the game ends costs you its points.</p>`],
    ['End of the game', 'Scoring', `<p>The end is triggered as soon as a farmer has delivered ${R.ordersToEnd} orders, or a fruit runs out entirely. Finish the round so every farmer has had the same number of turns, then score.</p><p>Add the points on your delivered cards and take away the points of every secret order still in your hand. The most points wins. If farmers tie, the fuller basket wins; if still tied, the farmer who took their turn later in the round wins.</p><p>The game also ends after ${R.rounds} rounds.</p>`],
    ['At a glance', 'Turn summary', `<ol><li>Walk up to ${R.moves} trees.</li><li>Pick one fruit (not under the crow); basket of ${R.basket}.</li><li>Deliver an order if you can; refill the market.</li><li>Fly the crow 1 to ${R.crowMoves} trees on; a farmer there gives you a fruit.</li></ol><p>${R.ordersToEnd} orders delivered or an empty fruit ends the game at the end of the round. Delivered points, less any secret order still in hand.</p>`],
  ];
  return { lid, pages };
});
